const path = require('path')
const ava = require('ava')
const fs = require('fs-extra')
const sinon = require('sinon')
const jsdock = require('../')

ava('generates & publishes docs', async t => {
  const outputDirname = path.join(__dirname, '../docs')
  const stub = sinon.stub(jsdock, '_ghPublish').returns(() => Promise.resolve())
  await jsdock.clean()
  let docsExist = await fs.exists(outputDirname)
  t.falsy(docsExist, 'docs not present on init')
  await jsdock.build()
  docsExist = await fs.exists(outputDirname)
  t.truthy(docsExist, 'docs generated')
  await jsdock.publish()
  t.truthy(stub.calledOnce, 'published called once')
  stub.restore()
  await jsdock.clean()
  docsExist = await fs.exists(outputDirname)
  t.falsy(docsExist, 'docs not present on clean')
})
